---
deployment:
  tasks:
    - >
      if command -v composer >/dev/null 2>&1; then
        composer install --no-dev --optimize-autoloader;
      elif [ -x /opt/cpanel/composer/bin/composer ]; then
        /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader;
      else
        echo "Composer no está disponible" >&2; exit 1;
      fi

    - >
      rsync -av --delete \
        --exclude='.git' \
        --exclude='.gitignore' \
        --exclude='.cpanel.yml' \
        --exclude='README_*' \
        --exclude='error_log' \
        --exclude='config/mail.php' \
        ./ "/home/fupeseco/public_html"
