---
deployment:
  tasks:
    - |
      set -e

      # AJUSTA ESTA RUTA al document root real
      DEPLOYPATH=/home/fupeseco/public_html   # <-- o /home/fupeseco/public_html/fupese

      echo "Repositorio: $(pwd)"
      echo "Destino: $DEPLOYPATH"

      # Marca de prueba
      echo "Último deploy: $(date)" > "$DEPLOYPATH/deploy-info.txt"

      rsync -av --delete \
        --exclude='.git' \
        --exclude='.gitignore' \
        --exclude='.cpanel.yml' \
        --exclude='README_*' \
        --exclude='error_log' \
        ./ "$DEPLOYPATH"
