---
deployment:
  tasks:
    - |
      set -e

      DEPLOYPATH=/home/fupeseco/public_html

      echo "Repositorio: $(pwd)"
      echo "Destino: $DEPLOYPATH"

      rsync -av --delete \
        --exclude='.git' \
        --exclude='.gitignore' \
        --exclude='.cpanel.yml' \
        --exclude='README_*' \
        --exclude='error_log' \
        ./ "$DEPLOYPATH"
