---
deployment:
  tasks:
    - |
      set -e

      # Ajusta la ruta de destino según tu dominio
      DEPLOYPATH=/home/fupeseco/public_html

      echo "Repositorio: $(pwd)"
      echo "Destino: $DEPLOYPATH"

      # 1) Instalar dependencias PHP con Composer (si hay composer.json)
      if [ -f composer.json ]; then
        if command -v composer >/dev/null 2>&1; then
          composer install --no-dev --optimize-autoloader
        elif [ -x /opt/cpanel/composer/bin/composer ]; then
          /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
        else
          echo "Composer no está disponible" >&2
          exit 1
        fi
      else
        echo "No hay composer.json, se omite Composer"
      fi

      # 2) Sincronizar código al public_html
      rsync -av --delete \
        --exclude='.git' \
        --exclude='.gitignore' \
        --exclude='.cpanel.yml' \
        --exclude='README_*' \
        --exclude='error_log' \
        ./ "$DEPLOYPATH"
