---
deployment:
  tasks:
    # Ruta de despliegue en cPanel (ajusta con tu usuario si cambia la home)
    - export DEPLOYPATH=/home/$USER/public_html/

    # Instala dependencias PHP (usa Composer de cPanel si está disponible)
    - >
      if command -v composer >/dev/null 2>&1; then
        composer install --no-dev --optimize-autoloader;
      elif [ -x /opt/cpanel/composer/bin/composer ]; then
        /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader;
      else
        echo "Composer no está disponible" >&2; exit 1;
      fi

    # Sincroniza el código hacia el public_html sin sobrescribir tu config local
    - >
      rsync -av --delete \
        --exclude='.git' \
        --exclude='.gitignore' \
        --exclude='.cpanel.yml' \
        --exclude='README_*' \
        --exclude='error_log' \
        --exclude='config/mail.php' \
        ./ "$DEPLOYPATH"
