---
deployment:
  tasks:
    - |
      set -e

      # Log sencillo para verificar que el deploy corrió
      echo "Iniciando deploy: $(date)" >> /home/fupeseco/deploy-debug.log

      # Sincronizar el repo hacia public_html
      rsync -av --delete \
        --exclude='.git' \
        --exclude='.gitignore' \
        --exclude='.cpanel.yml' \
        --exclude='README_*' \
        --exclude='error_log' \
        /home/fupeseco/repositories/fupese/ /home/fupeseco/public_html/
